
                var state = [
                {abrev: "" , state: "Select ..."},
                {abrev: "AK" , state: "Alaska"},
                {abrev: "AL" , state: "Alabama"}, 
                {abrev: "AR" , state: "Arkansas"}, 
                {abrev: "AS" , state: "American Samoa"}, 
                {abrev: "AZ" , state: "Arizona"}, 
                {abrev: "CA" , state: "California"}, 
                {abrev: "CO" , state: "Colorado"}, 
                {abrev: "CT" , state: "Connecticut"}, 
                {abrev: "DC" , state: "District of Columbia"}, 
                {abrev: "DE" , state: "Delaware"}, 
                {abrev: "FL" , state: "Florida"}, 
                {abrev: "GA" , state: "Georgia"}, 
                {abrev: "GU" , state: "Guam"}, 
                {abrev: "HI" , state: "Hawaii"}, 
                {abrev: "IA" , state: "Iowa"}, 
                {abrev: "ID" , state: "Idaho"}, 
                {abrev: "IL" , state: "Illinois"}, 
                {abrev: "IN" , state: "Indiana"}, 
                {abrev: "KS" , state: "Kansas"}, 
                {abrev: "KY" , state: "Kentucky"}, 
                {abrev: "LA" , state: "Louisiana"}, 
                {abrev: "MA" , state: "Massachusetts"}, 
                {abrev: "MD" , state: "Maryland"}, 
                {abrev: "ME" , state: "Maine"}, 
                {abrev: "MI" , state: "Michigan"}, 
                {abrev: "MN" , state: "Minnesota"}, 
                {abrev: "MO" , state: "Missouri"}, 
                {abrev: "MS" , state: "Mississippi"}, 
                {abrev: "MT" , state: "Montana"}, 
                {abrev: "NC" , state: "North Carolina"}, 
                {abrev: "ND" , state: "North Dakota"}, 
                {abrev: "NE" , state: "Nebraska"}, 
                {abrev: "NH" , state: "New Hampshire"}, 
                {abrev: "NJ" , state: "New Jersey"}, 
                {abrev: "NM" , state: "New Mexico"}, 
                {abrev: "NV" , state: "Nevada"}, 
                {abrev: "NY" , state: "New York"}, 
                {abrev: "OH" , state: "Ohio"}, 
                {abrev: "OK" , state: "Oklahoma"}, 
                {abrev: "OR" , state: "Oregon"}, 
                {abrev: "PA" , state: "Pennsylvania"}, 
                {abrev: "PR" , state: "Puerto Rico"}, 
                {abrev: "RI" , state: "Rhode Island"}, 
                {abrev: "SC" , state: "South Carolina"}, 
                {abrev: "SD" , state: "South Dakota"}, 
                {abrev: "TN" , state: "Tennessee"}, 
                {abrev: "TX" , state: "Texas"}, 
                {abrev: "UT" , state: "Utah"}, 
                {abrev: "VA" , state: "Virginia"}, 
                {abrev: "VI" , state: "Virgin Islands"}, 
                {abrev: "VT" , state: "Vermont"}, 
                {abrev: "WA" , state: "Washington"}, 
                {abrev: "WI" , state: "Wisconsin"}, 
                {abrev: "WV" , state: "West Virginia"}, 
                {abrev: "WY" , state: "Wyoming"}
                ];
                